### ISSUE TITLE
pycuda error

### ISSUE THREAD

**Issue by donjiaking** [JOP-Lee/READ#12]
when I run `CUDA_DEVICE=0 python viewer.py --config downloads/kitti6.yaml` on a remote server with X-11 forwarding, I met the following problem.
I use `sh requirement.sh` to install the environment.
I wonder how to solve it. Thanks.

```
loading pointcloud...
no normals in Data/kitti6/pointcloud.ply
=== 3D model ===
VERTICES:  2547322
EXTENT:  [ -84.91281891  -12.33472538 -234.02790833] [ 68.9091568   47.1550293  685.07629395]
================
new viewport size  (1216, 368)
[w] Cannot read STENCIL size from the framebuffer
[i] Using GLFW (GL 3.1)
Traceback (most recent call last):
  File "/home/user/working/NeRF/READ/READ/gl/render.py", line 29, in _init_buffers
    import pycuda.gl.autoinit  # this may fails in headless mode
  File "/root/anaconda3/envs/READ/lib/python3.9/site-packages/pycuda-2022.2-py3.9-linux-x86_64.egg/pycuda/gl/autoinit.py", line 10, in <module>
    context = make_default_context(lambda dev: cudagl.make_context(dev))
  File "/root/anaconda3/envs/READ/lib/python3.9/site-packages/pycuda-2022.2-py3.9-linux-x86_64.egg/pycuda/tools.py", line 215, in make_default_context
    return ctx_maker(dev)
  File "/root/anaconda3/envs/READ/lib/python3.9/site-packages/pycuda-2022.2-py3.9-linux-x86_64.egg/pycuda/gl/autoinit.py", line 10, in <lambda>
    context = make_default_context(lambda dev: cudagl.make_context(dev))
pycuda._driver.LogicError: cuGLCtxCreate failed: OS call failed or operation not supported on this OS
```

**Comment by JOP-Lee** [comment]
Maybe it's the lack of a monitor, you need to set it to headless mode
