### ISSUE TITLE
  File "/SHFP12/02_bevdet/READ_02/READ/gl/render.py", line 31, in _init_buffers     raise RuntimeError('PyCUDA init failed, cannot use torch buffer') RuntimeError: PyCUDA init failed, cannot use torch buffer

### ISSUE THREAD

**Issue by rockywind** [JOP-Lee/READ#15]
Hi,
When I follow the install guide, I met the error below.
I run 'python viewer.py --config downloads/kitti6.yaml' in Mobaxtem.
```
READ_02$ python viewer_debug.py
loading pointcloud...
no normals in /READ/Data/image_kitti6_all_368/pointcloud.ply
=== 3D model ===
VERTICES:  2547322
EXTENT:  [ -84.91281891  -12.33472538 -234.02790833] [ 68.9091568   47.1550293  685.07629395]
================
new viewport size  (1216, 368)
[w] Cannot read STENCIL size from the framebuffer
[i] Using GLFW (GL 3.0)
Traceback (most recent call last):
  File "/SHFP12/02_bevdet/READ_02/READ/gl/render.py", line 29, in _init_buffers
    import pycuda.gl.autoinit  # this may fails in headless mode
  File "/anaconda3/envs/Oflow/lib/python3.7/site-packages/pycuda-2022.2-py3.7-linux-x86_64.egg/pycuda/g                                           l/autoinit.py", line 10, in <module>
    context = make_default_context(lambda dev: cudagl.make_context(dev))
  File "anaconda3/envs/Oflow/lib/python3.7/site-packages/pycuda-2022.2-py3.7-linux-x86_64.egg/pycuda/t                                           ools.py", line 228, in make_default_context
    "on any of the %d detected devices" % ndevices
RuntimeError: make_default_context() wasn't able to create a context on any of the 1 detected devices

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "viewer_debug.py", line 555, in <module>
    my_app = MyApp(args)
  File "viewer_debug.py", line 187, in __init__
    clear_color=args.clear_color)
  File "/SHFP12/02_bevdet/READ_02/READ/gl/render.py", line 19, in __init__
    self._init_buffers(viewport_size, out_buffer_location)
  File "/SHFP12/02_bevdet/READ_02/READ/gl/render.py", line 31, in _init_buffers
    raise RuntimeError('PyCUDA init failed, cannot use torch buffer')
RuntimeError: PyCUDA init failed, cannot use torch buffer

```

**Comment by dq2b25** [comment]
I meet the same problem too

**Comment by wuzuyin** [comment]
> I meet the same problem......

Hello, have you solved this problem

**Comment by wuzuyin** [comment]
> Hello, have you solved this proble

Hello, have you solved this problem

**Comment by wuzuyin** [comment]
> I meet the same problem too

Hello, have you solved this problem

**Comment by vinodrajendran001** [comment]
I am also facing the same issue

**Comment by booker-max** [comment]
I meet the same problem, have you solved this problem

**Comment by vikamllbyy** [comment]
Hello everyone

What I did to solve this problem was found on the internet, so the only thing to do is add this as a prefix before the original command:

__NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia python viewer.py --config downloads/kitti6.yaml

After this, it seems that the problem is fixed. Im not sure if is the best solution, but I think it works. If someone could test it for feedback. 

Also, after this, I get another warning abot data/logs/path
but it also was solved changing the config file "kitti6.yaml" where is described the direction path. And also this gave me another error. 

RuntimeError: CUDA error: no kernel image is available for execution on the device 
And then when it was solved finally get 

RuntimeError: CUDA out of memory 

So, If anyone could help to solve this last one? , I know it's clearly related to my GPU, but I don't know how to solve it yet

**Comment by vikamllbyy** [comment]
> Hello everyone
> 
> What I did to solve this problem was found on the internet, so the only thing to do is add this as a prefix before the original command:
> 
> __NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia python viewer.py --config downloads/kitti6.yaml
> 
> After this, it seems that the problem is fixed. Im not sure if is the best solution, but I think it works. If someone could test it for feedback.
> 
> Also, after this, I get another warning abot data/logs/path but it also was solved changing the config file "kitti6.yaml" where is described the direction path. And also this gave me another error.
> 
> RuntimeError: CUDA error: no kernel image is available for execution on the device And then when it was solved finally get
> 
> RuntimeError: CUDA out of memory
> 
> So, If anyone could help to solve this last one? , I know it's clearly related to my GPU, but I don't know how to solve it yet
@vinodrajendran001 @booker-max @JOP-Lee

**Comment by Fireworker20th** [comment]
Hello everyone, I believe I've resolved this issue. For more information about this problem, please refer to issue #12 on the npbg project on GitHub. The author has provided modifications, specifically in the MyAPP class. However, there are differences in the viewer.py in the read directory, so you also need to add the 'numpy' part to the on_draw function. Please avoid making changes in the 'src' directory. Wishing everyone success!

**Comment by Neronjust2017** [comment]
> on_draw
Hi, are you referring to this issue? https://github.com/alievk/npbg/issues/12. Did you use the following viewer.py instead? https://gist.github.com/seva100/93e8c4bdc5f929f1790e370542ab101f

**Comment by Neronjust2017** [comment]
> Hello everyone, I believe I've resolved this issue. For more information about this problem, please refer to issue #12 on the npbg project on GitHub. The author has provided modifications, specifically in the MyAPP class. However, there are differences in the viewer.py in the read directory, so you also need to add the 'numpy' part to the on_draw function. Please avoid making changes in the 'src' directory. Wishing everyone success!

@Fireworker20th  Hi, are you referring to this issue? https://github.com/alievk/npbg/issues/12. Did you use the following viewer.py instead? https://gist.github.com/seva100/93e8c4bdc5f929f1790e370542ab101f
