### ISSUE TITLE
there is no file named "pointcloud.ply"

### ISSUE THREAD

**Issue by LittleStoneAtGithub** [JOP-Lee/READ#17]
I get this error when I run "python viewer.py --config downloads/kitti6.yaml"  
  
  
loading pointcloud...
Traceback (most recent call last):
  File "/home/oscar/src/deeplearning/READ/viewer.py", line 551, in <module>
    my_app = MyApp(args)
  File "/home/oscar/src/deeplearning/READ/viewer.py", line 118, in __init__
    self.scene_data = load_scene_data(args.config)
  File "/home/oscar/src/deeplearning/READ/READ/gl/utils.py", line 264, in load_scene_data
    pointcloud = import_model3d(fix_relative_path(config['pointcloud'], path))
  File "/home/oscar/src/deeplearning/READ/READ/gl/utils.py", line 397, in import_model3d
    data = trimesh.load(model_path)
  File "/home/oscar/anaconda3/envs/READ/lib/python3.9/site-packages/trimesh/exchange/load.py", line 113, in load
    ) = parse_file_args(file_obj=file_obj,
  File "/home/oscar/anaconda3/envs/READ/lib/python3.9/site-packages/trimesh/exchange/load.py", line 627, in parse_file_args
    raise ValueError('string is not a file: {}'.format(file_obj))
ValueError: string is not a file: Data/kitti6_368_total/pointcloud.ply

It seems that there is only "scene.yam" in "Data" directory...

**Comment by JOP-Lee** [comment]
https://zenodo.org/record/7395608#.Y7mEmXZBxPZ
